# Generated by Django 3.1.7 on 2021-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviews_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_type',
            field=models.CharField(choices=[('review', 'review'), ('suggestion', 'suggestion')], max_length=10, verbose_name='Review Type: '),
        ),
    ]
