# Generated by Django 3.1.7 on 2021-04-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210414_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('permalink', models.CharField(max_length=20, unique=True, verbose_name='Permalink')),
                ('nav_title', models.CharField(max_length=60, verbose_name='Navigation Title')),
                ('main_text', models.TextField(blank=True, verbose_name='Main Text')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_type',
            field=models.CharField(choices=[('suggestion', 'suggestion'), ('review', 'review')], max_length=10, verbose_name='Review Type: '),
        ),
    ]
