# Generated by Django 3.1.7 on 2021-04-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210415_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(default='Unknown', max_length=60, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_type',
            field=models.CharField(choices=[('suggestion', 'suggestion'), ('review', 'review')], max_length=10, verbose_name='Review Type'),
        ),
    ]
