# Generated by Django 3.1.7 on 2021-04-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesinfo',
            name='creation_date',
            field=models.DateField(blank=True, verbose_name='Date of creation'),
        ),
    ]
