# Generated by Django 3.1.7 on 2021-04-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210411_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesinfo',
            name='image_file',
            field=models.ImageField(upload_to='uploaded_images/', verbose_name='File'),
        ),
    ]
