# Generated by Django 3.1.7 on 2021-04-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20210411_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesinfo',
            name='theme_link',
            field=models.CharField(blank=True, choices=[('inktober', 'inktober'), ('huevember', 'huevember'), ('', '')], max_length=60, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='imagesinfo',
            name='year_link',
            field=models.CharField(choices=[('2016', '2016'), ('2017', '2017'), ('2019', '2019'), ('2018', '2018'), ('2020', '2020'), ('2021', '2021')], max_length=60, verbose_name='Year'),
        ),
    ]
