# Generated by Django 3.1.7 on 2021-04-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20210415_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesinfo',
            name='year_link',
            field=models.CharField(choices=[('2016', '2016'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2017', '2017'), ('2018', '2018')], max_length=60, verbose_name='Year'),
        ),
    ]
