# Generated by Django 3.1.7 on 2021-04-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('permalink', models.CharField(max_length=20, unique=True, verbose_name='Permalink')),
                ('main_text', models.TextField(blank=True, verbose_name='Main Text')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
    ]
