# Generated by Django 3.1.7 on 2021-04-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('nav_title', models.CharField(max_length=60, verbose_name='Navigation Title')),
                ('permalink', models.CharField(max_length=20, unique=True, verbose_name='Permalink')),
                ('year', models.CharField(max_length=60, verbose_name='Year Title')),
                ('main_text', models.TextField(blank=True, verbose_name='Main Text')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
    ]
