# Generated by Django 3.1.7 on 2021-04-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years_db', '0002_themesinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesinfo',
            name='permalink',
            field=models.CharField(max_length=20, verbose_name='Permalink'),
        ),
    ]
