# Generated by Django 3.1.7 on 2021-04-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years_db', '0003_auto_20210410_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesinfo',
            name='year',
            field=models.CharField(choices=[('2017', '2017'), ('2019', '2019'), ('2018', '2018'), ('- 2016', '2016'), ('2020', '2020'), ('2021', '2021')], max_length=60, verbose_name='Year Title'),
        ),
    ]
