# Generated by Django 3.1.7 on 2021-04-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='main_page_dialog',
            field=models.CharField(default=2, max_length=60, verbose_name='Dialog Title'),
            preserve_default=False,
        ),
    ]
