# Generated by Django 3.1.7 on 2021-04-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_info', '0002_pageinfo_main_page_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinfo',
            name='main_page_dialog',
            field=models.CharField(blank=True, max_length=60, verbose_name='Dialog Title'),
        ),
    ]
